// File generated by the BNF Converter (bnfc 2.9.4).

package lama;

/** All Visitor */

public interface AllVisitor<R,A> extends
  lama.Absyn.Program.Visitor<R,A>,
  lama.Absyn.Stm.Visitor<R,A>,
  lama.Absyn.Exp.Visitor<R,A>,
  lama.Absyn.Bool.Visitor<R,A>,
  lama.Absyn.Type.Visitor<R,A>
{}
