// File generated by the BNF Converter (bnfc 2.9.4).

package lama;
/** Composition Visitor
*/

public class ComposVisitor<A> implements
  lama.Absyn.Program.Visitor<lama.Absyn.Program,A>,
  lama.Absyn.Stm.Visitor<lama.Absyn.Stm,A>,
  lama.Absyn.Exp.Visitor<lama.Absyn.Exp,A>,
  lama.Absyn.Bool.Visitor<lama.Absyn.Bool,A>,
  lama.Absyn.Type.Visitor<lama.Absyn.Type,A>
{
    /* Program */
    public lama.Absyn.Program visit(lama.Absyn.Prog p, A arg)
    {
      lama.Absyn.ListStm liststm_ = new lama.Absyn.ListStm();
      for (lama.Absyn.Stm x : p.liststm_)
      {
        liststm_.add(x.accept(this,arg));
      }
      return new lama.Absyn.Prog(liststm_);
    }

    /* Stm */
    public lama.Absyn.Stm visit(lama.Absyn.SExp p, A arg)
    {
      lama.Absyn.Exp exp_ = p.exp_.accept(this, arg);
      return new lama.Absyn.SExp(exp_);
    }
    public lama.Absyn.Stm visit(lama.Absyn.SDecl p, A arg)
    {
      lama.Absyn.Type type_ = p.type_.accept(this, arg);
      String ident_ = p.ident_;
      return new lama.Absyn.SDecl(type_, ident_);
    }
    public lama.Absyn.Stm visit(lama.Absyn.SAss p, A arg)
    {
      String ident_ = p.ident_;
      lama.Absyn.Exp exp_ = p.exp_.accept(this, arg);
      return new lama.Absyn.SAss(ident_, exp_);
    }
    public lama.Absyn.Stm visit(lama.Absyn.SInit p, A arg)
    {
      lama.Absyn.Type type_ = p.type_.accept(this, arg);
      String ident_ = p.ident_;
      lama.Absyn.Exp exp_ = p.exp_.accept(this, arg);
      return new lama.Absyn.SInit(type_, ident_, exp_);
    }
    public lama.Absyn.Stm visit(lama.Absyn.SPrint p, A arg)
    {
      lama.Absyn.Exp exp_ = p.exp_.accept(this, arg);
      return new lama.Absyn.SPrint(exp_);
    }
    public lama.Absyn.Stm visit(lama.Absyn.SWhile p, A arg)
    {
      lama.Absyn.Exp exp_ = p.exp_.accept(this, arg);
      lama.Absyn.Stm stm_ = p.stm_.accept(this, arg);
      return new lama.Absyn.SWhile(exp_, stm_);
    }
    public lama.Absyn.Stm visit(lama.Absyn.SBlock p, A arg)
    {
      lama.Absyn.ListStm liststm_ = new lama.Absyn.ListStm();
      for (lama.Absyn.Stm x : p.liststm_)
      {
        liststm_.add(x.accept(this,arg));
      }
      return new lama.Absyn.SBlock(liststm_);
    }
    public lama.Absyn.Stm visit(lama.Absyn.SReturn p, A arg)
    {
      lama.Absyn.Exp exp_ = p.exp_.accept(this, arg);
      return new lama.Absyn.SReturn(exp_);
    }
    public lama.Absyn.Stm visit(lama.Absyn.SIfElse p, A arg)
    {
      lama.Absyn.Exp exp_ = p.exp_.accept(this, arg);
      lama.Absyn.Stm stm_1 = p.stm_1.accept(this, arg);
      lama.Absyn.Stm stm_2 = p.stm_2.accept(this, arg);
      return new lama.Absyn.SIfElse(exp_, stm_1, stm_2);
    }
    public lama.Absyn.Stm visit(lama.Absyn.SFun p, A arg)
    {
      lama.Absyn.Type type_1 = p.type_1.accept(this, arg);
      String ident_1 = p.ident_1;
      lama.Absyn.Type type_2 = p.type_2.accept(this, arg);
      String ident_2 = p.ident_2;
      lama.Absyn.ListStm liststm_ = new lama.Absyn.ListStm();
      for (lama.Absyn.Stm x : p.liststm_)
      {
        liststm_.add(x.accept(this,arg));
      }
      return new lama.Absyn.SFun(type_1, ident_1, type_2, ident_2, liststm_);
    }
    public lama.Absyn.Stm visit(lama.Absyn.SImp p, A arg)
    {
      String string_ = p.string_;
      return new lama.Absyn.SImp(string_);
    }

    /* Exp */
    public lama.Absyn.Exp visit(lama.Absyn.EVar p, A arg)
    {
      String ident_ = p.ident_;
      return new lama.Absyn.EVar(ident_);
    }
    public lama.Absyn.Exp visit(lama.Absyn.EInt p, A arg)
    {
      Integer integer_ = p.integer_;
      return new lama.Absyn.EInt(integer_);
    }
    public lama.Absyn.Exp visit(lama.Absyn.EDouble p, A arg)
    {
      Double double_ = p.double_;
      return new lama.Absyn.EDouble(double_);
    }
    public lama.Absyn.Exp visit(lama.Absyn.EBool p, A arg)
    {
      lama.Absyn.Bool bool_ = p.bool_.accept(this, arg);
      return new lama.Absyn.EBool(bool_);
    }
    public lama.Absyn.Exp visit(lama.Absyn.EPostIncr p, A arg)
    {
      String ident_ = p.ident_;
      return new lama.Absyn.EPostIncr(ident_);
    }
    public lama.Absyn.Exp visit(lama.Absyn.EPostDecr p, A arg)
    {
      String ident_ = p.ident_;
      return new lama.Absyn.EPostDecr(ident_);
    }
    public lama.Absyn.Exp visit(lama.Absyn.EPreIncr p, A arg)
    {
      String ident_ = p.ident_;
      return new lama.Absyn.EPreIncr(ident_);
    }
    public lama.Absyn.Exp visit(lama.Absyn.EPreDecr p, A arg)
    {
      String ident_ = p.ident_;
      return new lama.Absyn.EPreDecr(ident_);
    }
    public lama.Absyn.Exp visit(lama.Absyn.EMul p, A arg)
    {
      lama.Absyn.Exp exp_1 = p.exp_1.accept(this, arg);
      lama.Absyn.Exp exp_2 = p.exp_2.accept(this, arg);
      return new lama.Absyn.EMul(exp_1, exp_2);
    }
    public lama.Absyn.Exp visit(lama.Absyn.EDiv p, A arg)
    {
      lama.Absyn.Exp exp_1 = p.exp_1.accept(this, arg);
      lama.Absyn.Exp exp_2 = p.exp_2.accept(this, arg);
      return new lama.Absyn.EDiv(exp_1, exp_2);
    }
    public lama.Absyn.Exp visit(lama.Absyn.EAdd p, A arg)
    {
      lama.Absyn.Exp exp_1 = p.exp_1.accept(this, arg);
      lama.Absyn.Exp exp_2 = p.exp_2.accept(this, arg);
      return new lama.Absyn.EAdd(exp_1, exp_2);
    }
    public lama.Absyn.Exp visit(lama.Absyn.ESub p, A arg)
    {
      lama.Absyn.Exp exp_1 = p.exp_1.accept(this, arg);
      lama.Absyn.Exp exp_2 = p.exp_2.accept(this, arg);
      return new lama.Absyn.ESub(exp_1, exp_2);
    }
    public lama.Absyn.Exp visit(lama.Absyn.ELess p, A arg)
    {
      lama.Absyn.Exp exp_1 = p.exp_1.accept(this, arg);
      lama.Absyn.Exp exp_2 = p.exp_2.accept(this, arg);
      return new lama.Absyn.ELess(exp_1, exp_2);
    }
    public lama.Absyn.Exp visit(lama.Absyn.EGreater p, A arg)
    {
      lama.Absyn.Exp exp_1 = p.exp_1.accept(this, arg);
      lama.Absyn.Exp exp_2 = p.exp_2.accept(this, arg);
      return new lama.Absyn.EGreater(exp_1, exp_2);
    }
    public lama.Absyn.Exp visit(lama.Absyn.ELEq p, A arg)
    {
      lama.Absyn.Exp exp_1 = p.exp_1.accept(this, arg);
      lama.Absyn.Exp exp_2 = p.exp_2.accept(this, arg);
      return new lama.Absyn.ELEq(exp_1, exp_2);
    }
    public lama.Absyn.Exp visit(lama.Absyn.EGEq p, A arg)
    {
      lama.Absyn.Exp exp_1 = p.exp_1.accept(this, arg);
      lama.Absyn.Exp exp_2 = p.exp_2.accept(this, arg);
      return new lama.Absyn.EGEq(exp_1, exp_2);
    }
    public lama.Absyn.Exp visit(lama.Absyn.EEq p, A arg)
    {
      lama.Absyn.Exp exp_1 = p.exp_1.accept(this, arg);
      lama.Absyn.Exp exp_2 = p.exp_2.accept(this, arg);
      return new lama.Absyn.EEq(exp_1, exp_2);
    }
    public lama.Absyn.Exp visit(lama.Absyn.ENEq p, A arg)
    {
      lama.Absyn.Exp exp_1 = p.exp_1.accept(this, arg);
      lama.Absyn.Exp exp_2 = p.exp_2.accept(this, arg);
      return new lama.Absyn.ENEq(exp_1, exp_2);
    }
    public lama.Absyn.Exp visit(lama.Absyn.EAnd p, A arg)
    {
      lama.Absyn.Exp exp_1 = p.exp_1.accept(this, arg);
      lama.Absyn.Exp exp_2 = p.exp_2.accept(this, arg);
      return new lama.Absyn.EAnd(exp_1, exp_2);
    }
    public lama.Absyn.Exp visit(lama.Absyn.EOr p, A arg)
    {
      lama.Absyn.Exp exp_1 = p.exp_1.accept(this, arg);
      lama.Absyn.Exp exp_2 = p.exp_2.accept(this, arg);
      return new lama.Absyn.EOr(exp_1, exp_2);
    }
    public lama.Absyn.Exp visit(lama.Absyn.Array p, A arg)
    {
      lama.Absyn.Type type_ = p.type_.accept(this, arg);
      lama.Absyn.ListExp listexp_ = new lama.Absyn.ListExp();
      for (lama.Absyn.Exp x : p.listexp_)
      {
        listexp_.add(x.accept(this,arg));
      }
      return new lama.Absyn.Array(type_, listexp_);
    }
    public lama.Absyn.Exp visit(lama.Absyn.Append p, A arg)
    {
      lama.Absyn.Exp exp_1 = p.exp_1.accept(this, arg);
      lama.Absyn.Exp exp_2 = p.exp_2.accept(this, arg);
      return new lama.Absyn.Append(exp_1, exp_2);
    }
    public lama.Absyn.Exp visit(lama.Absyn.Head p, A arg)
    {
      lama.Absyn.Exp exp_ = p.exp_.accept(this, arg);
      return new lama.Absyn.Head(exp_);
    }
    public lama.Absyn.Exp visit(lama.Absyn.IsEmpty p, A arg)
    {
      lama.Absyn.Exp exp_ = p.exp_.accept(this, arg);
      return new lama.Absyn.IsEmpty(exp_);
    }
    public lama.Absyn.Exp visit(lama.Absyn.Last p, A arg)
    {
      lama.Absyn.Exp exp_ = p.exp_.accept(this, arg);
      return new lama.Absyn.Last(exp_);
    }

    /* Bool */
    public lama.Absyn.Bool visit(lama.Absyn.Bool_true p, A arg)
    {
      return new lama.Absyn.Bool_true();
    }
    public lama.Absyn.Bool visit(lama.Absyn.Bool_false p, A arg)
    {
      return new lama.Absyn.Bool_false();
    }

    /* Type */
    public lama.Absyn.Type visit(lama.Absyn.TInt p, A arg)
    {
      return new lama.Absyn.TInt();
    }
    public lama.Absyn.Type visit(lama.Absyn.TDouble p, A arg)
    {
      return new lama.Absyn.TDouble();
    }
    public lama.Absyn.Type visit(lama.Absyn.TBool p, A arg)
    {
      return new lama.Absyn.TBool();
    }
    public lama.Absyn.Type visit(lama.Absyn.TArray p, A arg)
    {
      lama.Absyn.Type type_ = p.type_.accept(this, arg);
      return new lama.Absyn.TArray(type_);
    }
}
