// -*- Java -*- File generated by the BNF Converter (bnfc 2.9.4).
// Lexer definition for use with JLex
package lama;
import java_cup.runtime.*;


public class Yylex implements java_cup.runtime.Scanner {
	private final int YY_BUFFER_SIZE = 512;
	private final int YY_F = -1;
	private final int YY_NO_STATE = -1;
	private final int YY_NOT_ACCEPT = 0;
	private final int YY_START = 1;
	private final int YY_END = 2;
	private final int YY_NO_ANCHOR = 4;
	private final int YY_BOL = 65536;
	private final int YY_EOF = 65537;

  String pstring = new String();
  final int unknown = -1;
  ComplexSymbolFactory.Location left = new ComplexSymbolFactory.Location(unknown, unknown);
  ComplexSymbolFactory cf = new ComplexSymbolFactory();
  public SymbolFactory getSymbolFactory() { return cf; }
  int yyline = unknown - 1;
  int yycolumn = unknown - 1;
  int yychar = unknown;
  public int line_num() { return (yyline+1); }
  public ComplexSymbolFactory.Location left_loc() {
    return left;
  }
  public ComplexSymbolFactory.Location right_loc() {
    ComplexSymbolFactory.Location left = left_loc();
  return left;
  }
  public String buff() {return new String(yy_buffer,yy_buffer_index,10).trim();}
	private java.io.BufferedReader yy_reader;
	private int yy_buffer_index;
	private int yy_buffer_read;
	private int yy_buffer_start;
	private int yy_buffer_end;
	private char yy_buffer[];
	private boolean yy_at_bol;
	private int yy_lexical_state;

	public Yylex (java.io.Reader reader) {
		this ();
		if (null == reader) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(reader);
	}

	public Yylex (java.io.InputStream instream) {
		this ();
		if (null == instream) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(new java.io.InputStreamReader(instream));
	}

	private Yylex () {
		yy_buffer = new char[YY_BUFFER_SIZE];
		yy_buffer_read = 0;
		yy_buffer_index = 0;
		yy_buffer_start = 0;
		yy_buffer_end = 0;
		yy_at_bol = true;
		yy_lexical_state = YYINITIAL;
	}

	private boolean yy_eof_done = false;
	private final int STRING = 5;
	private final int ESCAPED = 6;
	private final int YYINITIAL = 0;
	private final int COMMENT = 1;
	private final int CHAREND = 4;
	private final int CHARESC = 3;
	private final int CHAR = 2;
	private final int yy_state_dtrans[] = {
		0,
		105,
		106,
		106,
		106,
		107,
		108
	};
	private void yybegin (int state) {
		yy_lexical_state = state;
	}
	private int yy_advance ()
		throws java.io.IOException {
		int next_read;
		int i;
		int j;

		if (yy_buffer_index < yy_buffer_read) {
			return yy_buffer[yy_buffer_index++];
		}

		if (0 != yy_buffer_start) {
			i = yy_buffer_start;
			j = 0;
			while (i < yy_buffer_read) {
				yy_buffer[j] = yy_buffer[i];
				++i;
				++j;
			}
			yy_buffer_end = yy_buffer_end - yy_buffer_start;
			yy_buffer_start = 0;
			yy_buffer_read = j;
			yy_buffer_index = j;
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}

		while (yy_buffer_index >= yy_buffer_read) {
			if (yy_buffer_index >= yy_buffer.length) {
				yy_buffer = yy_double(yy_buffer);
			}
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}
		return yy_buffer[yy_buffer_index++];
	}
	private void yy_move_end () {
		if (yy_buffer_end > yy_buffer_start &&
		    '\n' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
		if (yy_buffer_end > yy_buffer_start &&
		    '\r' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
	}
	private boolean yy_last_was_cr=false;
	private void yy_mark_start () {
		yy_buffer_start = yy_buffer_index;
	}
	private void yy_mark_end () {
		yy_buffer_end = yy_buffer_index;
	}
	private void yy_to_mark () {
		yy_buffer_index = yy_buffer_end;
		yy_at_bol = (yy_buffer_end > yy_buffer_start) &&
		            ('\r' == yy_buffer[yy_buffer_end-1] ||
		             '\n' == yy_buffer[yy_buffer_end-1] ||
		             2028/*LS*/ == yy_buffer[yy_buffer_end-1] ||
		             2029/*PS*/ == yy_buffer[yy_buffer_end-1]);
	}
	private java.lang.String yytext () {
		return (new java.lang.String(yy_buffer,
			yy_buffer_start,
			yy_buffer_end - yy_buffer_start));
	}
	private int yylength () {
		return yy_buffer_end - yy_buffer_start;
	}
	private char[] yy_double (char buf[]) {
		int i;
		char newbuf[];
		newbuf = new char[2*buf.length];
		for (i = 0; i < buf.length; ++i) {
			newbuf[i] = buf[i];
		}
		return newbuf;
	}
	private final int YY_E_INTERNAL = 0;
	private final int YY_E_MATCH = 1;
	private java.lang.String yy_error_string[] = {
		"Error: Internal error.\n",
		"Error: Unmatched input.\n"
	};
	private void yy_error (int code,boolean fatal) {
		java.lang.System.out.print(yy_error_string[code]);
		java.lang.System.out.flush();
		if (fatal) {
			throw new Error("Fatal Error.\n");
		}
	}
	private int[][] unpackFromString(int size1, int size2, String st) {
		int colonIndex = -1;
		String lengthString;
		int sequenceLength = 0;
		int sequenceInteger = 0;

		int commaIndex;
		String workString;

		int res[][] = new int[size1][size2];
		for (int i= 0; i < size1; i++) {
			for (int j= 0; j < size2; j++) {
				if (sequenceLength != 0) {
					res[i][j] = sequenceInteger;
					sequenceLength--;
					continue;
				}
				commaIndex = st.indexOf(',');
				workString = (commaIndex==-1) ? st :
					st.substring(0, commaIndex);
				st = st.substring(commaIndex+1);
				colonIndex = workString.indexOf(':');
				if (colonIndex == -1) {
					res[i][j]=Integer.parseInt(workString);
					continue;
				}
				lengthString =
					workString.substring(colonIndex+1);
				sequenceLength=Integer.parseInt(lengthString);
				workString=workString.substring(0,colonIndex);
				sequenceInteger=Integer.parseInt(workString);
				res[i][j] = sequenceInteger;
				sequenceLength--;
			}
		}
		return res;
	}
	private int yy_acpt[] = {
		/* 0 */ YY_NOT_ACCEPT,
		/* 1 */ YY_NO_ANCHOR,
		/* 2 */ YY_NO_ANCHOR,
		/* 3 */ YY_NO_ANCHOR,
		/* 4 */ YY_NO_ANCHOR,
		/* 5 */ YY_NO_ANCHOR,
		/* 6 */ YY_NO_ANCHOR,
		/* 7 */ YY_NO_ANCHOR,
		/* 8 */ YY_NO_ANCHOR,
		/* 9 */ YY_NO_ANCHOR,
		/* 10 */ YY_NO_ANCHOR,
		/* 11 */ YY_NO_ANCHOR,
		/* 12 */ YY_NO_ANCHOR,
		/* 13 */ YY_NO_ANCHOR,
		/* 14 */ YY_NO_ANCHOR,
		/* 15 */ YY_NO_ANCHOR,
		/* 16 */ YY_NO_ANCHOR,
		/* 17 */ YY_NO_ANCHOR,
		/* 18 */ YY_NO_ANCHOR,
		/* 19 */ YY_NO_ANCHOR,
		/* 20 */ YY_NO_ANCHOR,
		/* 21 */ YY_NO_ANCHOR,
		/* 22 */ YY_NO_ANCHOR,
		/* 23 */ YY_NO_ANCHOR,
		/* 24 */ YY_NO_ANCHOR,
		/* 25 */ YY_NO_ANCHOR,
		/* 26 */ YY_NO_ANCHOR,
		/* 27 */ YY_NO_ANCHOR,
		/* 28 */ YY_NO_ANCHOR,
		/* 29 */ YY_NO_ANCHOR,
		/* 30 */ YY_NO_ANCHOR,
		/* 31 */ YY_NO_ANCHOR,
		/* 32 */ YY_NO_ANCHOR,
		/* 33 */ YY_NO_ANCHOR,
		/* 34 */ YY_NO_ANCHOR,
		/* 35 */ YY_NO_ANCHOR,
		/* 36 */ YY_NO_ANCHOR,
		/* 37 */ YY_NO_ANCHOR,
		/* 38 */ YY_NO_ANCHOR,
		/* 39 */ YY_NO_ANCHOR,
		/* 40 */ YY_NO_ANCHOR,
		/* 41 */ YY_NO_ANCHOR,
		/* 42 */ YY_NO_ANCHOR,
		/* 43 */ YY_NO_ANCHOR,
		/* 44 */ YY_NO_ANCHOR,
		/* 45 */ YY_NO_ANCHOR,
		/* 46 */ YY_NO_ANCHOR,
		/* 47 */ YY_NO_ANCHOR,
		/* 48 */ YY_NO_ANCHOR,
		/* 49 */ YY_NO_ANCHOR,
		/* 50 */ YY_NO_ANCHOR,
		/* 51 */ YY_NO_ANCHOR,
		/* 52 */ YY_NO_ANCHOR,
		/* 53 */ YY_NO_ANCHOR,
		/* 54 */ YY_NO_ANCHOR,
		/* 55 */ YY_NO_ANCHOR,
		/* 56 */ YY_NO_ANCHOR,
		/* 57 */ YY_NO_ANCHOR,
		/* 58 */ YY_NO_ANCHOR,
		/* 59 */ YY_NO_ANCHOR,
		/* 60 */ YY_NO_ANCHOR,
		/* 61 */ YY_NO_ANCHOR,
		/* 62 */ YY_NO_ANCHOR,
		/* 63 */ YY_NOT_ACCEPT,
		/* 64 */ YY_NO_ANCHOR,
		/* 65 */ YY_NO_ANCHOR,
		/* 66 */ YY_NO_ANCHOR,
		/* 67 */ YY_NO_ANCHOR,
		/* 68 */ YY_NO_ANCHOR,
		/* 69 */ YY_NO_ANCHOR,
		/* 70 */ YY_NOT_ACCEPT,
		/* 71 */ YY_NO_ANCHOR,
		/* 72 */ YY_NO_ANCHOR,
		/* 73 */ YY_NOT_ACCEPT,
		/* 74 */ YY_NO_ANCHOR,
		/* 75 */ YY_NO_ANCHOR,
		/* 76 */ YY_NOT_ACCEPT,
		/* 77 */ YY_NO_ANCHOR,
		/* 78 */ YY_NO_ANCHOR,
		/* 79 */ YY_NOT_ACCEPT,
		/* 80 */ YY_NO_ANCHOR,
		/* 81 */ YY_NOT_ACCEPT,
		/* 82 */ YY_NO_ANCHOR,
		/* 83 */ YY_NOT_ACCEPT,
		/* 84 */ YY_NO_ANCHOR,
		/* 85 */ YY_NOT_ACCEPT,
		/* 86 */ YY_NO_ANCHOR,
		/* 87 */ YY_NOT_ACCEPT,
		/* 88 */ YY_NO_ANCHOR,
		/* 89 */ YY_NOT_ACCEPT,
		/* 90 */ YY_NO_ANCHOR,
		/* 91 */ YY_NOT_ACCEPT,
		/* 92 */ YY_NO_ANCHOR,
		/* 93 */ YY_NOT_ACCEPT,
		/* 94 */ YY_NOT_ACCEPT,
		/* 95 */ YY_NOT_ACCEPT,
		/* 96 */ YY_NOT_ACCEPT,
		/* 97 */ YY_NOT_ACCEPT,
		/* 98 */ YY_NOT_ACCEPT,
		/* 99 */ YY_NOT_ACCEPT,
		/* 100 */ YY_NOT_ACCEPT,
		/* 101 */ YY_NOT_ACCEPT,
		/* 102 */ YY_NOT_ACCEPT,
		/* 103 */ YY_NOT_ACCEPT,
		/* 104 */ YY_NOT_ACCEPT,
		/* 105 */ YY_NOT_ACCEPT,
		/* 106 */ YY_NOT_ACCEPT,
		/* 107 */ YY_NOT_ACCEPT,
		/* 108 */ YY_NOT_ACCEPT,
		/* 109 */ YY_NO_ANCHOR,
		/* 110 */ YY_NOT_ACCEPT,
		/* 111 */ YY_NOT_ACCEPT,
		/* 112 */ YY_NO_ANCHOR,
		/* 113 */ YY_NOT_ACCEPT,
		/* 114 */ YY_NO_ANCHOR,
		/* 115 */ YY_NO_ANCHOR,
		/* 116 */ YY_NO_ANCHOR,
		/* 117 */ YY_NO_ANCHOR,
		/* 118 */ YY_NO_ANCHOR,
		/* 119 */ YY_NO_ANCHOR,
		/* 120 */ YY_NO_ANCHOR,
		/* 121 */ YY_NO_ANCHOR,
		/* 122 */ YY_NOT_ACCEPT,
		/* 123 */ YY_NO_ANCHOR,
		/* 124 */ YY_NO_ANCHOR,
		/* 125 */ YY_NO_ANCHOR,
		/* 126 */ YY_NO_ANCHOR,
		/* 127 */ YY_NO_ANCHOR,
		/* 128 */ YY_NO_ANCHOR,
		/* 129 */ YY_NO_ANCHOR,
		/* 130 */ YY_NO_ANCHOR,
		/* 131 */ YY_NO_ANCHOR,
		/* 132 */ YY_NOT_ACCEPT,
		/* 133 */ YY_NO_ANCHOR,
		/* 134 */ YY_NO_ANCHOR,
		/* 135 */ YY_NO_ANCHOR,
		/* 136 */ YY_NO_ANCHOR,
		/* 137 */ YY_NO_ANCHOR,
		/* 138 */ YY_NO_ANCHOR,
		/* 139 */ YY_NO_ANCHOR
	};
	private int yy_cmap[] = unpackFromString(1,65538,
"40:9,47,41,40,47,39,40:18,47,13,42,40:3,14,46,3,4,9,7,33,8,18,10,44:10,40,1" +
",11,2,12,40:2,45:4,29,45:21,16,43,17,40,46,40,19,34,45,23,21,24,45,38,25,45" +
":2,32,30,22,35,20,45,26,27,28,36,45,37,45,31,45,5,15,6,40:66,45:23,40,45:31" +
",40,45:8,40:65280,0:2")[0];

	private int yy_rmap[] = unpackFromString(1,140,
"0,1:2,2,1:4,3,4,1,5,6,7,8,1:2,9,1:3,10,1:4,11,1:5,9:2,12,9:9,1:8,13,1:7,14," +
"1:2,15,16,17,18,19,1:2,20,21,22,23,24,25,26,1,27,28,29,30,31,32,33,34,35,36" +
",37,38,39,40,41,42,43,44,18,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60" +
",61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85" +
",86,87")[0];

	private int yy_nxt[][] = unpackFromString(88,48,
"1,2,3,4,5,6,7,8,9,10,11,12,13,14,64,71,15,16,74,17,131,121,17,138,133,65,13" +
"9,17,123,17:4,18,124,17:2,134,17,19,77,19,20,77,21,17,77,19,-1:50,22,-1:52," +
"23,-1:48,24,-1:48,25,26,-1:39,27,-1:47,28,-1:47,29,-1:64,17:14,-1,17:5,-1:5" +
",17:3,-1:19,79,-1:25,21,-1:4,26:40,-1,26:6,-1:21,93,-1:22,34,-1:44,68,-1:47" +
",69,-1:26,110,-1:41,30,-1:52,17:3,72,17,32,17:5,136,17:2,-1,17:5,-1:5,17:3," +
"-1:45,66,-1:13,50,-1:62,81,-1:37,31,-1:51,17:9,33,17:4,-1,17:5,-1:5,17:3,-1" +
":28,83,-1:39,63,-1:4,70,73,-1:6,76,-1:34,17:2,35,17:11,-1,17:5,-1:5,17:3,-1" +
":20,85,-1:47,17:2,36,17:11,-1,17:5,-1:5,17:3,-1:45,34,-1:22,17:13,37,-1,17:" +
"5,-1:5,17:3,-1:27,132,-1:40,17:9,38,17:4,-1,17:5,-1:5,17:3,-1:30,89,-1:37,1" +
"7:2,39,17:11,-1,17:5,-1:5,17:3,-1:28,91,-1:39,17:2,40,17:11,-1,17:5,-1:5,17" +
":3,-1:22,94,-1:45,17:2,41,17:11,-1,17:5,-1:5,17:3,-1:31,113,-1:36,17:9,42,1" +
"7:4,-1,17:5,-1:5,17:3,-1:29,95,-1:38,17:3,43,17:10,-1,17:5,-1:5,17:3,-1:9,9" +
"6,-1:35,66,-1:25,97,-1:28,99,-1:67,100,-1:52,102,-1:23,44,-1:46,45,-1:48,46" +
",-1:74,103,-1:19,104,-1:48,47,-1:43,1,48:8,67,48:29,-1,48,49,48:6,1,77:38,-" +
"1,77,-1,77:6,1,51:38,52,51,68,53,54,51:4,1,55:21,56,55,57,55,58,55,59,55:10" +
",60,55,69,61,62,55:4,-1:19,17:8,75,17:5,-1,17:5,-1:5,17:3,-1:21,87,-1:30,10" +
"1,-1:63,17:14,-1,17:2,78,17:2,-1:5,17:3,-1:21,98,-1:46,17:14,-1,17,80,17:3," +
"-1:5,17:3,-1:20,17:3,82,17:10,-1,17:5,-1:5,17:3,-1:20,17:8,84,17:5,-1,17:5," +
"-1:5,17:3,-1:20,17:13,86,-1,17:5,-1:5,17:3,-1:20,17:13,88,-1,17:5,-1:5,17:3" +
",-1:20,17:7,90,17:6,-1,17:5,-1:5,17:3,-1:20,17:7,92,17:6,-1,17:5,-1:5,17:3," +
"-1:20,17:13,109,-1,17:5,-1:5,17:3,-1:29,111,-1:38,17:7,112,17:6,-1,17:5,-1:" +
"5,17:3,-1:20,17:14,-1,17,114,17:3,-1:5,17:3,-1:20,17:6,115,17:7,-1,17:5,-1:" +
"5,17:3,-1:20,17:13,116,-1,17:5,-1:5,17:3,-1:20,17:6,117,17:7,-1,17:5,-1:5,1" +
"7:3,-1:20,17:14,-1,118,17:4,-1:5,17:3,-1:20,17:14,-1,17,119,17:3,-1:5,17:3," +
"-1:20,17:14,-1,17:2,120,17:2,-1:5,17:3,-1:20,17:7,125,17:6,-1,17:5,-1:5,17:" +
"3,-1:28,122,-1:39,126,17:13,-1,17:5,-1:5,17:3,-1:20,17:14,-1,17:4,127,-1:5," +
"17:3,-1:20,17:14,-1,17:2,128,17:2,-1:5,17:3,-1:20,17,129,17:12,-1,17:5,-1:5" +
",17:3,-1:20,17:9,130,17:4,-1,17:5,-1:5,17:3,-1:20,17:14,-1,17,135,17:3,-1:5" +
",17:3,-1:20,17:2,137,17:11,-1,17:5,-1:5,17:3,-1");

	public java_cup.runtime.Symbol next_token ()
		throws java.io.IOException {
		int yy_lookahead;
		int yy_anchor = YY_NO_ANCHOR;
		int yy_state = yy_state_dtrans[yy_lexical_state];
		int yy_next_state = YY_NO_STATE;
		int yy_last_accept_state = YY_NO_STATE;
		boolean yy_initial = true;
		int yy_this_accept;

		yy_mark_start();
		yy_this_accept = yy_acpt[yy_state];
		if (YY_NOT_ACCEPT != yy_this_accept) {
			yy_last_accept_state = yy_state;
			yy_mark_end();
		}
		while (true) {
			if (yy_initial && yy_at_bol) yy_lookahead = YY_BOL;
			else yy_lookahead = yy_advance();
			yy_next_state = YY_F;
			yy_next_state = yy_nxt[yy_rmap[yy_state]][yy_cmap[yy_lookahead]];
			if (YY_EOF == yy_lookahead && true == yy_initial) {

  return cf.newSymbol("EOF", sym.EOF, left_loc(), left_loc());
			}
			if (YY_F != yy_next_state) {
				yy_state = yy_next_state;
				yy_initial = false;
				yy_this_accept = yy_acpt[yy_state];
				if (YY_NOT_ACCEPT != yy_this_accept) {
					yy_last_accept_state = yy_state;
					yy_mark_end();
				}
			}
			else {
				if (YY_NO_STATE == yy_last_accept_state) {
					throw (new Error("Lexical Error: Unmatched Input."));
				}
				else {
					yy_anchor = yy_acpt[yy_last_accept_state];
					if (0 != (YY_END & yy_anchor)) {
						yy_move_end();
					}
					yy_to_mark();
					switch (yy_last_accept_state) {
					case 1:
						
					case -2:
						break;
					case 2:
						{ return cf.newSymbol("", sym._SYMB_0, left_loc(), right_loc()); }
					case -3:
						break;
					case 3:
						{ return cf.newSymbol("", sym._SYMB_1, left_loc(), right_loc()); }
					case -4:
						break;
					case 4:
						{ return cf.newSymbol("", sym._SYMB_2, left_loc(), right_loc()); }
					case -5:
						break;
					case 5:
						{ return cf.newSymbol("", sym._SYMB_3, left_loc(), right_loc()); }
					case -6:
						break;
					case 6:
						{ return cf.newSymbol("", sym._SYMB_4, left_loc(), right_loc()); }
					case -7:
						break;
					case 7:
						{ return cf.newSymbol("", sym._SYMB_5, left_loc(), right_loc()); }
					case -8:
						break;
					case 8:
						{ return cf.newSymbol("", sym._SYMB_10, left_loc(), right_loc()); }
					case -9:
						break;
					case 9:
						{ return cf.newSymbol("", sym._SYMB_11, left_loc(), right_loc()); }
					case -10:
						break;
					case 10:
						{ return cf.newSymbol("", sym._SYMB_8, left_loc(), right_loc()); }
					case -11:
						break;
					case 11:
						{ return cf.newSymbol("", sym._SYMB_9, left_loc(), right_loc()); }
					case -12:
						break;
					case 12:
						{ return cf.newSymbol("", sym._SYMB_12, left_loc(), right_loc()); }
					case -13:
						break;
					case 13:
						{ return cf.newSymbol("", sym._SYMB_13, left_loc(), right_loc()); }
					case -14:
						break;
					case 14:
						{ throw new Error("Illegal Character <"+yytext()+">"); }
					case -15:
						break;
					case 15:
						{ return cf.newSymbol("", sym._SYMB_20, left_loc(), right_loc()); }
					case -16:
						break;
					case 16:
						{ return cf.newSymbol("", sym._SYMB_21, left_loc(), right_loc()); }
					case -17:
						break;
					case 17:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -18:
						break;
					case 18:
						{ return cf.newSymbol("", sym._SYMB_26, left_loc(), right_loc()); }
					case -19:
						break;
					case 19:
						{ /* ignore white space. */ }
					case -20:
						break;
					case 20:
						{ left = left_loc(); yybegin(STRING); }
					case -21:
						break;
					case 21:
						{ return cf.newSymbol("", sym._INTEGER_, left_loc(), right_loc(), Integer.valueOf(yytext())); }
					case -22:
						break;
					case 22:
						{ return cf.newSymbol("", sym._SYMB_16, left_loc(), right_loc()); }
					case -23:
						break;
					case 23:
						{ return cf.newSymbol("", sym._SYMB_6, left_loc(), right_loc()); }
					case -24:
						break;
					case 24:
						{ return cf.newSymbol("", sym._SYMB_7, left_loc(), right_loc()); }
					case -25:
						break;
					case 25:
						{ yybegin(COMMENT); }
					case -26:
						break;
					case 26:
						{ /* skip */ }
					case -27:
						break;
					case 27:
						{ return cf.newSymbol("", sym._SYMB_14, left_loc(), right_loc()); }
					case -28:
						break;
					case 28:
						{ return cf.newSymbol("", sym._SYMB_15, left_loc(), right_loc()); }
					case -29:
						break;
					case 29:
						{ return cf.newSymbol("", sym._SYMB_17, left_loc(), right_loc()); }
					case -30:
						break;
					case 30:
						{ return cf.newSymbol("", sym._SYMB_18, left_loc(), right_loc()); }
					case -31:
						break;
					case 31:
						{ return cf.newSymbol("", sym._SYMB_19, left_loc(), right_loc()); }
					case -32:
						break;
					case 32:
						{ return cf.newSymbol("", sym._SYMB_31, left_loc(), right_loc()); }
					case -33:
						break;
					case 33:
						{ return cf.newSymbol("", sym._SYMB_33, left_loc(), right_loc()); }
					case -34:
						break;
					case 34:
						{ return cf.newSymbol("", sym._DOUBLE_, left_loc(), right_loc(), Double.valueOf(yytext())); }
					case -35:
						break;
					case 35:
						{ return cf.newSymbol("", sym._SYMB_29, left_loc(), right_loc()); }
					case -36:
						break;
					case 36:
						{ return cf.newSymbol("", sym._SYMB_36, left_loc(), right_loc()); }
					case -37:
						break;
					case 37:
						{ return cf.newSymbol("", sym._SYMB_27, left_loc(), right_loc()); }
					case -38:
						break;
					case 38:
						{ return cf.newSymbol("", sym._SYMB_34, left_loc(), right_loc()); }
					case -39:
						break;
					case 39:
						{ return cf.newSymbol("", sym._SYMB_30, left_loc(), right_loc()); }
					case -40:
						break;
					case 40:
						{ return cf.newSymbol("", sym._SYMB_37, left_loc(), right_loc()); }
					case -41:
						break;
					case 41:
						{ return cf.newSymbol("", sym._SYMB_28, left_loc(), right_loc()); }
					case -42:
						break;
					case 42:
						{ return cf.newSymbol("", sym._SYMB_32, left_loc(), right_loc()); }
					case -43:
						break;
					case 43:
						{ return cf.newSymbol("", sym._SYMB_35, left_loc(), right_loc()); }
					case -44:
						break;
					case 44:
						{ return cf.newSymbol("", sym._SYMB_25, left_loc(), right_loc()); }
					case -45:
						break;
					case 45:
						{ return cf.newSymbol("", sym._SYMB_22, left_loc(), right_loc()); }
					case -46:
						break;
					case 46:
						{ return cf.newSymbol("", sym._SYMB_23, left_loc(), right_loc()); }
					case -47:
						break;
					case 47:
						{ return cf.newSymbol("", sym._SYMB_24, left_loc(), right_loc()); }
					case -48:
						break;
					case 48:
						{ /* skip */ }
					case -49:
						break;
					case 49:
						{ /* skip */ }
					case -50:
						break;
					case 50:
						{ yybegin(YYINITIAL); }
					case -51:
						break;
					case 51:
						{ pstring += yytext(); }
					case -52:
						break;
					case 52:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -53:
						break;
					case 53:
						{ String foo = pstring; pstring = new String(); yybegin(YYINITIAL); return cf.newSymbol("", sym._STRING_, left, right_loc(), foo.intern()); }
					case -54:
						break;
					case 54:
						{ yybegin(ESCAPED); }
					case -55:
						break;
					case 55:
						{ pstring += yytext(); yybegin(STRING); }
					case -56:
						break;
					case 56:
						{ pstring +=  "\n"; yybegin(STRING); }
					case -57:
						break;
					case 57:
						{ pstring += "\f"; yybegin(STRING); }
					case -58:
						break;
					case 58:
						{ pstring += "\r"; yybegin(STRING); }
					case -59:
						break;
					case 59:
						{ pstring += "\t"; yybegin(STRING); }
					case -60:
						break;
					case 60:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -61:
						break;
					case 61:
						{ pstring += "\""; yybegin(STRING); }
					case -62:
						break;
					case 62:
						{ pstring += "\\"; yybegin(STRING); }
					case -63:
						break;
					case 64:
						{ throw new Error("Illegal Character <"+yytext()+">"); }
					case -64:
						break;
					case 65:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -65:
						break;
					case 66:
						{ return cf.newSymbol("", sym._DOUBLE_, left_loc(), right_loc(), Double.valueOf(yytext())); }
					case -66:
						break;
					case 67:
						{ /* skip */ }
					case -67:
						break;
					case 68:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -68:
						break;
					case 69:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -69:
						break;
					case 71:
						{ throw new Error("Illegal Character <"+yytext()+">"); }
					case -70:
						break;
					case 72:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -71:
						break;
					case 74:
						{ throw new Error("Illegal Character <"+yytext()+">"); }
					case -72:
						break;
					case 75:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -73:
						break;
					case 77:
						{ throw new Error("Illegal Character <"+yytext()+">"); }
					case -74:
						break;
					case 78:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -75:
						break;
					case 80:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -76:
						break;
					case 82:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -77:
						break;
					case 84:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -78:
						break;
					case 86:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -79:
						break;
					case 88:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -80:
						break;
					case 90:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -81:
						break;
					case 92:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -82:
						break;
					case 109:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -83:
						break;
					case 112:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -84:
						break;
					case 114:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -85:
						break;
					case 115:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -86:
						break;
					case 116:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -87:
						break;
					case 117:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -88:
						break;
					case 118:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -89:
						break;
					case 119:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -90:
						break;
					case 120:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -91:
						break;
					case 121:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -92:
						break;
					case 123:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -93:
						break;
					case 124:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -94:
						break;
					case 125:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -95:
						break;
					case 126:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -96:
						break;
					case 127:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -97:
						break;
					case 128:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -98:
						break;
					case 129:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -99:
						break;
					case 130:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -100:
						break;
					case 131:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -101:
						break;
					case 133:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -102:
						break;
					case 134:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -103:
						break;
					case 135:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -104:
						break;
					case 136:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -105:
						break;
					case 137:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -106:
						break;
					case 138:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -107:
						break;
					case 139:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -108:
						break;
					default:
						yy_error(YY_E_INTERNAL,false);
					case -1:
					}
					yy_initial = true;
					yy_state = yy_state_dtrans[yy_lexical_state];
					yy_next_state = YY_NO_STATE;
					yy_last_accept_state = YY_NO_STATE;
					yy_mark_start();
					yy_this_accept = yy_acpt[yy_state];
					if (YY_NOT_ACCEPT != yy_this_accept) {
						yy_last_accept_state = yy_state;
						yy_mark_end();
					}
				}
			}
		}
	}
}
