// -*- Java -*- File generated by the BNF Converter (bnfc 2.9.4).
// Lexer definition for use with JLex
package lama;
import java_cup.runtime.*;


public class Yylex implements java_cup.runtime.Scanner {
	private final int YY_BUFFER_SIZE = 512;
	private final int YY_F = -1;
	private final int YY_NO_STATE = -1;
	private final int YY_NOT_ACCEPT = 0;
	private final int YY_START = 1;
	private final int YY_END = 2;
	private final int YY_NO_ANCHOR = 4;
	private final int YY_BOL = 65536;
	private final int YY_EOF = 65537;

  String pstring = new String();
  final int unknown = -1;
  ComplexSymbolFactory.Location left = new ComplexSymbolFactory.Location(unknown, unknown);
  ComplexSymbolFactory cf = new ComplexSymbolFactory();
  public SymbolFactory getSymbolFactory() { return cf; }
  int yyline = unknown - 1;
  int yycolumn = unknown - 1;
  int yychar = unknown;
  public int line_num() { return (yyline+1); }
  public ComplexSymbolFactory.Location left_loc() {
    return left;
  }
  public ComplexSymbolFactory.Location right_loc() {
    ComplexSymbolFactory.Location left = left_loc();
  return left;
  }
  public String buff() {return new String(yy_buffer,yy_buffer_index,10).trim();}
	private java.io.BufferedReader yy_reader;
	private int yy_buffer_index;
	private int yy_buffer_read;
	private int yy_buffer_start;
	private int yy_buffer_end;
	private char yy_buffer[];
	private boolean yy_at_bol;
	private int yy_lexical_state;

	public Yylex (java.io.Reader reader) {
		this ();
		if (null == reader) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(reader);
	}

	public Yylex (java.io.InputStream instream) {
		this ();
		if (null == instream) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(new java.io.InputStreamReader(instream));
	}

	private Yylex () {
		yy_buffer = new char[YY_BUFFER_SIZE];
		yy_buffer_read = 0;
		yy_buffer_index = 0;
		yy_buffer_start = 0;
		yy_buffer_end = 0;
		yy_at_bol = true;
		yy_lexical_state = YYINITIAL;
	}

	private boolean yy_eof_done = false;
	private final int STRING = 4;
	private final int ESCAPED = 5;
	private final int YYINITIAL = 0;
	private final int CHAREND = 3;
	private final int CHARESC = 2;
	private final int CHAR = 1;
	private final int yy_state_dtrans[] = {
		0,
		82,
		82,
		82,
		82,
		82
	};
	private void yybegin (int state) {
		yy_lexical_state = state;
	}
	private int yy_advance ()
		throws java.io.IOException {
		int next_read;
		int i;
		int j;

		if (yy_buffer_index < yy_buffer_read) {
			return yy_buffer[yy_buffer_index++];
		}

		if (0 != yy_buffer_start) {
			i = yy_buffer_start;
			j = 0;
			while (i < yy_buffer_read) {
				yy_buffer[j] = yy_buffer[i];
				++i;
				++j;
			}
			yy_buffer_end = yy_buffer_end - yy_buffer_start;
			yy_buffer_start = 0;
			yy_buffer_read = j;
			yy_buffer_index = j;
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}

		while (yy_buffer_index >= yy_buffer_read) {
			if (yy_buffer_index >= yy_buffer.length) {
				yy_buffer = yy_double(yy_buffer);
			}
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}
		return yy_buffer[yy_buffer_index++];
	}
	private void yy_move_end () {
		if (yy_buffer_end > yy_buffer_start &&
		    '\n' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
		if (yy_buffer_end > yy_buffer_start &&
		    '\r' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
	}
	private boolean yy_last_was_cr=false;
	private void yy_mark_start () {
		yy_buffer_start = yy_buffer_index;
	}
	private void yy_mark_end () {
		yy_buffer_end = yy_buffer_index;
	}
	private void yy_to_mark () {
		yy_buffer_index = yy_buffer_end;
		yy_at_bol = (yy_buffer_end > yy_buffer_start) &&
		            ('\r' == yy_buffer[yy_buffer_end-1] ||
		             '\n' == yy_buffer[yy_buffer_end-1] ||
		             2028/*LS*/ == yy_buffer[yy_buffer_end-1] ||
		             2029/*PS*/ == yy_buffer[yy_buffer_end-1]);
	}
	private java.lang.String yytext () {
		return (new java.lang.String(yy_buffer,
			yy_buffer_start,
			yy_buffer_end - yy_buffer_start));
	}
	private int yylength () {
		return yy_buffer_end - yy_buffer_start;
	}
	private char[] yy_double (char buf[]) {
		int i;
		char newbuf[];
		newbuf = new char[2*buf.length];
		for (i = 0; i < buf.length; ++i) {
			newbuf[i] = buf[i];
		}
		return newbuf;
	}
	private final int YY_E_INTERNAL = 0;
	private final int YY_E_MATCH = 1;
	private java.lang.String yy_error_string[] = {
		"Error: Internal error.\n",
		"Error: Unmatched input.\n"
	};
	private void yy_error (int code,boolean fatal) {
		java.lang.System.out.print(yy_error_string[code]);
		java.lang.System.out.flush();
		if (fatal) {
			throw new Error("Fatal Error.\n");
		}
	}
	private int[][] unpackFromString(int size1, int size2, String st) {
		int colonIndex = -1;
		String lengthString;
		int sequenceLength = 0;
		int sequenceInteger = 0;

		int commaIndex;
		String workString;

		int res[][] = new int[size1][size2];
		for (int i= 0; i < size1; i++) {
			for (int j= 0; j < size2; j++) {
				if (sequenceLength != 0) {
					res[i][j] = sequenceInteger;
					sequenceLength--;
					continue;
				}
				commaIndex = st.indexOf(',');
				workString = (commaIndex==-1) ? st :
					st.substring(0, commaIndex);
				st = st.substring(commaIndex+1);
				colonIndex = workString.indexOf(':');
				if (colonIndex == -1) {
					res[i][j]=Integer.parseInt(workString);
					continue;
				}
				lengthString =
					workString.substring(colonIndex+1);
				sequenceLength=Integer.parseInt(lengthString);
				workString=workString.substring(0,colonIndex);
				sequenceInteger=Integer.parseInt(workString);
				res[i][j] = sequenceInteger;
				sequenceLength--;
			}
		}
		return res;
	}
	private int yy_acpt[] = {
		/* 0 */ YY_NOT_ACCEPT,
		/* 1 */ YY_NO_ANCHOR,
		/* 2 */ YY_NO_ANCHOR,
		/* 3 */ YY_NO_ANCHOR,
		/* 4 */ YY_NO_ANCHOR,
		/* 5 */ YY_NO_ANCHOR,
		/* 6 */ YY_NO_ANCHOR,
		/* 7 */ YY_NO_ANCHOR,
		/* 8 */ YY_NO_ANCHOR,
		/* 9 */ YY_NO_ANCHOR,
		/* 10 */ YY_NO_ANCHOR,
		/* 11 */ YY_NO_ANCHOR,
		/* 12 */ YY_NO_ANCHOR,
		/* 13 */ YY_NO_ANCHOR,
		/* 14 */ YY_NO_ANCHOR,
		/* 15 */ YY_NO_ANCHOR,
		/* 16 */ YY_NO_ANCHOR,
		/* 17 */ YY_NO_ANCHOR,
		/* 18 */ YY_NO_ANCHOR,
		/* 19 */ YY_NO_ANCHOR,
		/* 20 */ YY_NO_ANCHOR,
		/* 21 */ YY_NO_ANCHOR,
		/* 22 */ YY_NO_ANCHOR,
		/* 23 */ YY_NO_ANCHOR,
		/* 24 */ YY_NO_ANCHOR,
		/* 25 */ YY_NO_ANCHOR,
		/* 26 */ YY_NO_ANCHOR,
		/* 27 */ YY_NO_ANCHOR,
		/* 28 */ YY_NO_ANCHOR,
		/* 29 */ YY_NO_ANCHOR,
		/* 30 */ YY_NO_ANCHOR,
		/* 31 */ YY_NO_ANCHOR,
		/* 32 */ YY_NO_ANCHOR,
		/* 33 */ YY_NO_ANCHOR,
		/* 34 */ YY_NO_ANCHOR,
		/* 35 */ YY_NO_ANCHOR,
		/* 36 */ YY_NO_ANCHOR,
		/* 37 */ YY_NO_ANCHOR,
		/* 38 */ YY_NO_ANCHOR,
		/* 39 */ YY_NO_ANCHOR,
		/* 40 */ YY_NO_ANCHOR,
		/* 41 */ YY_NO_ANCHOR,
		/* 42 */ YY_NO_ANCHOR,
		/* 43 */ YY_NO_ANCHOR,
		/* 44 */ YY_NOT_ACCEPT,
		/* 45 */ YY_NO_ANCHOR,
		/* 46 */ YY_NO_ANCHOR,
		/* 47 */ YY_NO_ANCHOR,
		/* 48 */ YY_NOT_ACCEPT,
		/* 49 */ YY_NO_ANCHOR,
		/* 50 */ YY_NO_ANCHOR,
		/* 51 */ YY_NOT_ACCEPT,
		/* 52 */ YY_NO_ANCHOR,
		/* 53 */ YY_NO_ANCHOR,
		/* 54 */ YY_NOT_ACCEPT,
		/* 55 */ YY_NO_ANCHOR,
		/* 56 */ YY_NO_ANCHOR,
		/* 57 */ YY_NOT_ACCEPT,
		/* 58 */ YY_NO_ANCHOR,
		/* 59 */ YY_NOT_ACCEPT,
		/* 60 */ YY_NO_ANCHOR,
		/* 61 */ YY_NOT_ACCEPT,
		/* 62 */ YY_NO_ANCHOR,
		/* 63 */ YY_NOT_ACCEPT,
		/* 64 */ YY_NO_ANCHOR,
		/* 65 */ YY_NOT_ACCEPT,
		/* 66 */ YY_NO_ANCHOR,
		/* 67 */ YY_NOT_ACCEPT,
		/* 68 */ YY_NO_ANCHOR,
		/* 69 */ YY_NOT_ACCEPT,
		/* 70 */ YY_NOT_ACCEPT,
		/* 71 */ YY_NOT_ACCEPT,
		/* 72 */ YY_NOT_ACCEPT,
		/* 73 */ YY_NOT_ACCEPT,
		/* 74 */ YY_NOT_ACCEPT,
		/* 75 */ YY_NOT_ACCEPT,
		/* 76 */ YY_NOT_ACCEPT,
		/* 77 */ YY_NOT_ACCEPT,
		/* 78 */ YY_NOT_ACCEPT,
		/* 79 */ YY_NOT_ACCEPT,
		/* 80 */ YY_NOT_ACCEPT,
		/* 81 */ YY_NOT_ACCEPT,
		/* 82 */ YY_NOT_ACCEPT,
		/* 83 */ YY_NO_ANCHOR,
		/* 84 */ YY_NOT_ACCEPT,
		/* 85 */ YY_NOT_ACCEPT,
		/* 86 */ YY_NO_ANCHOR,
		/* 87 */ YY_NOT_ACCEPT,
		/* 88 */ YY_NO_ANCHOR,
		/* 89 */ YY_NO_ANCHOR,
		/* 90 */ YY_NO_ANCHOR,
		/* 91 */ YY_NO_ANCHOR,
		/* 92 */ YY_NO_ANCHOR,
		/* 93 */ YY_NO_ANCHOR,
		/* 94 */ YY_NO_ANCHOR,
		/* 95 */ YY_NOT_ACCEPT,
		/* 96 */ YY_NO_ANCHOR,
		/* 97 */ YY_NO_ANCHOR,
		/* 98 */ YY_NO_ANCHOR,
		/* 99 */ YY_NO_ANCHOR,
		/* 100 */ YY_NO_ANCHOR,
		/* 101 */ YY_NO_ANCHOR,
		/* 102 */ YY_NO_ANCHOR,
		/* 103 */ YY_NO_ANCHOR,
		/* 104 */ YY_NOT_ACCEPT,
		/* 105 */ YY_NO_ANCHOR,
		/* 106 */ YY_NO_ANCHOR,
		/* 107 */ YY_NO_ANCHOR,
		/* 108 */ YY_NO_ANCHOR,
		/* 109 */ YY_NO_ANCHOR,
		/* 110 */ YY_NO_ANCHOR
	};
	private int yy_cmap[] = unpackFromString(1,65538,
"43:9,44,42,43,44,42,43:18,44,13,43:4,14,41,3,4,9,7,33,8,18,10,39:10,43,1,11" +
",2,12,43:2,40:4,29,40:21,16,43,17,43,41,43,19,34,40,23,21,24,40,38,25,40:2," +
"32,30,22,35,20,40,26,27,28,36,40,37,40,31,40,5,15,6,43:66,40:23,43,40:31,43" +
",40:8,43:65280,0:2")[0];

	private int yy_rmap[] = unpackFromString(1,111,
"0,1:2,2,1:4,3,4,1:2,5,6,7,1:2,8,1,9,1:9,8:2,10,8:8,1:4,11,12,13,14,15,16,17" +
",18,19,20,21,1,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,14,39,40," +
"41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65," +
"66,67,68,69,70,71,72,73,74,75")[0];

	private int yy_nxt[][] = unpackFromString(76,45,
"1,2,3,4,5,6,7,8,9,10,11,12,13,14,45,49,15,16,52,17,103,94,17,109,105,46,110" +
",17,96,17:4,18,97,17:2,106,17,19,17,55,20,55,20,-1:47,21,-1:49,22,-1:45,23," +
"-1:38,24,-1:44,25,-1:44,26,-1:61,17:14,-1,17:8,-1:21,57,-1:20,19,-1:26,70,-" +
"1:17,31,-1:25,84,-1:38,27,-1:49,17:3,50,17,29,17:8,-1,17:8,-1:42,47,-1:30,5" +
"9,-1:34,28,-1:48,17:9,30,17:4,-1,17:8,-1:30,61,-1:36,44,-1:4,48,51,-1:6,54," +
"-1:31,17:2,32,17:11,-1,17:8,-1:22,63,-1:44,17:2,33,17:11,-1,17:8,-1:42,31,-" +
"1:24,17:13,34,-1,17:8,-1:29,104,-1:37,17:9,35,17:4,-1,17:8,-1:32,67,-1:34,1" +
"7:2,36,17:11,-1,17:8,-1:30,69,-1:36,17:2,37,17:11,-1,17:8,-1:24,71,-1:42,17" +
":2,38,17:11,-1,17:8,-1:33,87,-1:33,17:3,39,17:10,-1,17:8,-1:31,72,-1:24,73," +
"-1:30,47,-1:27,74,-1:25,76,-1:64,77,-1:49,79,-1:20,40,-1:43,41,-1:45,42,-1:" +
"71,80,-1:16,81,-1:45,43,-1:40,1,55:41,-1,55:2,-1:19,17:8,53,17:5,-1,17:8,-1" +
":23,65,-1:27,78,-1:60,17:14,-1,17:2,56,17:5,-1:23,75,-1:43,17:14,-1,17,58,1" +
"7:6,-1:22,17:3,60,17:10,-1,17:8,-1:22,17:8,62,17:5,-1,17:8,-1:22,17:13,64,-" +
"1,17:8,-1:22,17:13,66,-1,17:8,-1:22,17:7,68,17:6,-1,17:8,-1:22,17:13,83,-1," +
"17:8,-1:31,85,-1:35,17:7,86,17:6,-1,17:8,-1:22,17:14,-1,17,88,17:6,-1:22,17" +
":6,89,17:7,-1,17:8,-1:22,17:13,90,-1,17:8,-1:22,17:6,91,17:7,-1,17:8,-1:22," +
"17:14,-1,92,17:7,-1:22,17:14,-1,17:2,93,17:5,-1:22,17:7,98,17:6,-1,17:8,-1:" +
"30,95,-1:36,99,17:13,-1,17:8,-1:22,17:14,-1,17:4,100,17:3,-1:22,17:14,-1,17" +
":2,101,17:5,-1:22,17:9,102,17:4,-1,17:8,-1:22,17:14,-1,17,107,17:6,-1:22,17" +
":2,108,17:11,-1,17:8,-1:3");

	public java_cup.runtime.Symbol next_token ()
		throws java.io.IOException {
		int yy_lookahead;
		int yy_anchor = YY_NO_ANCHOR;
		int yy_state = yy_state_dtrans[yy_lexical_state];
		int yy_next_state = YY_NO_STATE;
		int yy_last_accept_state = YY_NO_STATE;
		boolean yy_initial = true;
		int yy_this_accept;

		yy_mark_start();
		yy_this_accept = yy_acpt[yy_state];
		if (YY_NOT_ACCEPT != yy_this_accept) {
			yy_last_accept_state = yy_state;
			yy_mark_end();
		}
		while (true) {
			if (yy_initial && yy_at_bol) yy_lookahead = YY_BOL;
			else yy_lookahead = yy_advance();
			yy_next_state = YY_F;
			yy_next_state = yy_nxt[yy_rmap[yy_state]][yy_cmap[yy_lookahead]];
			if (YY_EOF == yy_lookahead && true == yy_initial) {

  return cf.newSymbol("EOF", sym.EOF, left_loc(), left_loc());
			}
			if (YY_F != yy_next_state) {
				yy_state = yy_next_state;
				yy_initial = false;
				yy_this_accept = yy_acpt[yy_state];
				if (YY_NOT_ACCEPT != yy_this_accept) {
					yy_last_accept_state = yy_state;
					yy_mark_end();
				}
			}
			else {
				if (YY_NO_STATE == yy_last_accept_state) {
					throw (new Error("Lexical Error: Unmatched Input."));
				}
				else {
					yy_anchor = yy_acpt[yy_last_accept_state];
					if (0 != (YY_END & yy_anchor)) {
						yy_move_end();
					}
					yy_to_mark();
					switch (yy_last_accept_state) {
					case 1:
						
					case -2:
						break;
					case 2:
						{ return cf.newSymbol("", sym._SYMB_0, left_loc(), right_loc()); }
					case -3:
						break;
					case 3:
						{ return cf.newSymbol("", sym._SYMB_1, left_loc(), right_loc()); }
					case -4:
						break;
					case 4:
						{ return cf.newSymbol("", sym._SYMB_2, left_loc(), right_loc()); }
					case -5:
						break;
					case 5:
						{ return cf.newSymbol("", sym._SYMB_3, left_loc(), right_loc()); }
					case -6:
						break;
					case 6:
						{ return cf.newSymbol("", sym._SYMB_4, left_loc(), right_loc()); }
					case -7:
						break;
					case 7:
						{ return cf.newSymbol("", sym._SYMB_5, left_loc(), right_loc()); }
					case -8:
						break;
					case 8:
						{ return cf.newSymbol("", sym._SYMB_10, left_loc(), right_loc()); }
					case -9:
						break;
					case 9:
						{ return cf.newSymbol("", sym._SYMB_11, left_loc(), right_loc()); }
					case -10:
						break;
					case 10:
						{ return cf.newSymbol("", sym._SYMB_8, left_loc(), right_loc()); }
					case -11:
						break;
					case 11:
						{ return cf.newSymbol("", sym._SYMB_9, left_loc(), right_loc()); }
					case -12:
						break;
					case 12:
						{ return cf.newSymbol("", sym._SYMB_12, left_loc(), right_loc()); }
					case -13:
						break;
					case 13:
						{ return cf.newSymbol("", sym._SYMB_13, left_loc(), right_loc()); }
					case -14:
						break;
					case 14:
						{ throw new Error("Illegal Character <"+yytext()+">"); }
					case -15:
						break;
					case 15:
						{ return cf.newSymbol("", sym._SYMB_20, left_loc(), right_loc()); }
					case -16:
						break;
					case 16:
						{ return cf.newSymbol("", sym._SYMB_21, left_loc(), right_loc()); }
					case -17:
						break;
					case 17:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -18:
						break;
					case 18:
						{ return cf.newSymbol("", sym._SYMB_26, left_loc(), right_loc()); }
					case -19:
						break;
					case 19:
						{ return cf.newSymbol("", sym._INTEGER_, left_loc(), right_loc(), Integer.valueOf(yytext())); }
					case -20:
						break;
					case 20:
						{ /* ignore white space. */ }
					case -21:
						break;
					case 21:
						{ return cf.newSymbol("", sym._SYMB_16, left_loc(), right_loc()); }
					case -22:
						break;
					case 22:
						{ return cf.newSymbol("", sym._SYMB_6, left_loc(), right_loc()); }
					case -23:
						break;
					case 23:
						{ return cf.newSymbol("", sym._SYMB_7, left_loc(), right_loc()); }
					case -24:
						break;
					case 24:
						{ return cf.newSymbol("", sym._SYMB_14, left_loc(), right_loc()); }
					case -25:
						break;
					case 25:
						{ return cf.newSymbol("", sym._SYMB_15, left_loc(), right_loc()); }
					case -26:
						break;
					case 26:
						{ return cf.newSymbol("", sym._SYMB_17, left_loc(), right_loc()); }
					case -27:
						break;
					case 27:
						{ return cf.newSymbol("", sym._SYMB_18, left_loc(), right_loc()); }
					case -28:
						break;
					case 28:
						{ return cf.newSymbol("", sym._SYMB_19, left_loc(), right_loc()); }
					case -29:
						break;
					case 29:
						{ return cf.newSymbol("", sym._SYMB_31, left_loc(), right_loc()); }
					case -30:
						break;
					case 30:
						{ return cf.newSymbol("", sym._SYMB_32, left_loc(), right_loc()); }
					case -31:
						break;
					case 31:
						{ return cf.newSymbol("", sym._DOUBLE_, left_loc(), right_loc(), Double.valueOf(yytext())); }
					case -32:
						break;
					case 32:
						{ return cf.newSymbol("", sym._SYMB_29, left_loc(), right_loc()); }
					case -33:
						break;
					case 33:
						{ return cf.newSymbol("", sym._SYMB_35, left_loc(), right_loc()); }
					case -34:
						break;
					case 34:
						{ return cf.newSymbol("", sym._SYMB_27, left_loc(), right_loc()); }
					case -35:
						break;
					case 35:
						{ return cf.newSymbol("", sym._SYMB_33, left_loc(), right_loc()); }
					case -36:
						break;
					case 36:
						{ return cf.newSymbol("", sym._SYMB_30, left_loc(), right_loc()); }
					case -37:
						break;
					case 37:
						{ return cf.newSymbol("", sym._SYMB_36, left_loc(), right_loc()); }
					case -38:
						break;
					case 38:
						{ return cf.newSymbol("", sym._SYMB_28, left_loc(), right_loc()); }
					case -39:
						break;
					case 39:
						{ return cf.newSymbol("", sym._SYMB_34, left_loc(), right_loc()); }
					case -40:
						break;
					case 40:
						{ return cf.newSymbol("", sym._SYMB_25, left_loc(), right_loc()); }
					case -41:
						break;
					case 41:
						{ return cf.newSymbol("", sym._SYMB_22, left_loc(), right_loc()); }
					case -42:
						break;
					case 42:
						{ return cf.newSymbol("", sym._SYMB_23, left_loc(), right_loc()); }
					case -43:
						break;
					case 43:
						{ return cf.newSymbol("", sym._SYMB_24, left_loc(), right_loc()); }
					case -44:
						break;
					case 45:
						{ throw new Error("Illegal Character <"+yytext()+">"); }
					case -45:
						break;
					case 46:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -46:
						break;
					case 47:
						{ return cf.newSymbol("", sym._DOUBLE_, left_loc(), right_loc(), Double.valueOf(yytext())); }
					case -47:
						break;
					case 49:
						{ throw new Error("Illegal Character <"+yytext()+">"); }
					case -48:
						break;
					case 50:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -49:
						break;
					case 52:
						{ throw new Error("Illegal Character <"+yytext()+">"); }
					case -50:
						break;
					case 53:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -51:
						break;
					case 55:
						{ throw new Error("Illegal Character <"+yytext()+">"); }
					case -52:
						break;
					case 56:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -53:
						break;
					case 58:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -54:
						break;
					case 60:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -55:
						break;
					case 62:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -56:
						break;
					case 64:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -57:
						break;
					case 66:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -58:
						break;
					case 68:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -59:
						break;
					case 83:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -60:
						break;
					case 86:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -61:
						break;
					case 88:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -62:
						break;
					case 89:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -63:
						break;
					case 90:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -64:
						break;
					case 91:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -65:
						break;
					case 92:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -66:
						break;
					case 93:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -67:
						break;
					case 94:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -68:
						break;
					case 96:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -69:
						break;
					case 97:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -70:
						break;
					case 98:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -71:
						break;
					case 99:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -72:
						break;
					case 100:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -73:
						break;
					case 101:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -74:
						break;
					case 102:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -75:
						break;
					case 103:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -76:
						break;
					case 105:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -77:
						break;
					case 106:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -78:
						break;
					case 107:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -79:
						break;
					case 108:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -80:
						break;
					case 109:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -81:
						break;
					case 110:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -82:
						break;
					default:
						yy_error(YY_E_INTERNAL,false);
					case -1:
					}
					yy_initial = true;
					yy_state = yy_state_dtrans[yy_lexical_state];
					yy_next_state = YY_NO_STATE;
					yy_last_accept_state = YY_NO_STATE;
					yy_mark_start();
					yy_this_accept = yy_acpt[yy_state];
					if (YY_NOT_ACCEPT != yy_this_accept) {
						yy_last_accept_state = yy_state;
						yy_mark_end();
					}
				}
			}
		}
	}
}
