## File generated by the BNF Converter (bnfc 2.9.4).

JAVAC=javac
JAVAC_FLAGS=-sourcepath .
JAVA=java
JAVA_FLAGS=
PARSER=${JAVA} ${JAVA_FLAGS} java_cup.Main
PARSER_FLAGS=-nopositions -expect 100
LEXER=${JAVA} ${JAVA_FLAGS} JLex.Main
LEXER_FLAGS=
all : test

test : absyn lama\Yylex.class lama\PrettyPrinter.class lama\Test.class lama\VisitSkel.class lama\ComposVisitor.class lama\AbstractVisitor.class lama\FoldVisitor.class lama\AllVisitor.class lama\parser.class lama\sym.class lama\Test.class

.PHONY : absyn

%.class : %.java
	${JAVAC} ${JAVAC_FLAGS} $^

absyn : lama\Absyn\Program.java lama\Absyn\Prog.java lama\Absyn\ListStm.java lama\Absyn\Stm.java lama\Absyn\SDecl.java lama\Absyn\SAss.java lama\Absyn\SInit.java lama\Absyn\SBlock.java lama\Absyn\SPrint.java lama\Absyn\Exp.java lama\Absyn\EVar.java lama\Absyn\EInt.java lama\Absyn\EDouble.java lama\Absyn\EBool.java lama\Absyn\EPostIncr.java lama\Absyn\EPostDecr.java lama\Absyn\EPreIncr.java lama\Absyn\EPreDecr.java lama\Absyn\EMul.java lama\Absyn\EDiv.java lama\Absyn\EAdd.java lama\Absyn\ESub.java lama\Absyn\ELess.java lama\Absyn\EGreater.java lama\Absyn\ELEq.java lama\Absyn\EGEq.java lama\Absyn\EEq.java lama\Absyn\ENEq.java lama\Absyn\Bool.java lama\Absyn\Bool_true.java lama\Absyn\Bool_false.java lama\Absyn\Type.java lama\Absyn\TInt.java lama\Absyn\TDouble.java lama\Absyn\TBool.java
	${JAVAC} ${JAVAC_FLAGS} $^

lama\Yylex.java : lama\Yylex
	${LEXER} ${LEXER_FLAGS} lama\Yylex

lama\parser.java lama\sym.java : lama\_cup.cup
	${PARSER} ${PARSER_FLAGS} lama\_cup.cup
	mv parser.java sym.java lama\

lama\Yylex.class : lama\Yylex.java lama\parser.java lama\sym.java

lama\sym.class : lama\sym.java

lama\parser.class : lama\parser.java lama\sym.java

lama\PrettyPrinter.class : lama\PrettyPrinter.java

clean :
	rm -f lama\Absyn\*.class lama\*.class

distclean : vclean

vclean :
	 rm -f lama\Absyn\Program.java lama\Absyn\Prog.java lama\Absyn\ListStm.java lama\Absyn\Stm.java lama\Absyn\SDecl.java lama\Absyn\SAss.java lama\Absyn\SInit.java lama\Absyn\SBlock.java lama\Absyn\SPrint.java lama\Absyn\Exp.java lama\Absyn\EVar.java lama\Absyn\EInt.java lama\Absyn\EDouble.java lama\Absyn\EBool.java lama\Absyn\EPostIncr.java lama\Absyn\EPostDecr.java lama\Absyn\EPreIncr.java lama\Absyn\EPreDecr.java lama\Absyn\EMul.java lama\Absyn\EDiv.java lama\Absyn\EAdd.java lama\Absyn\ESub.java lama\Absyn\ELess.java lama\Absyn\EGreater.java lama\Absyn\ELEq.java lama\Absyn\EGEq.java lama\Absyn\EEq.java lama\Absyn\ENEq.java lama\Absyn\Bool.java lama\Absyn\Bool_true.java lama\Absyn\Bool_false.java lama\Absyn\Type.java lama\Absyn\TInt.java lama\Absyn\TDouble.java lama\Absyn\TBool.java lama\Absyn\Program.class lama\Absyn\Prog.class lama\Absyn\ListStm.class lama\Absyn\Stm.class lama\Absyn\SDecl.class lama\Absyn\SAss.class lama\Absyn\SInit.class lama\Absyn\SBlock.class lama\Absyn\SPrint.class lama\Absyn\Exp.class lama\Absyn\EVar.class lama\Absyn\EInt.class lama\Absyn\EDouble.class lama\Absyn\EBool.class lama\Absyn\EPostIncr.class lama\Absyn\EPostDecr.class lama\Absyn\EPreIncr.class lama\Absyn\EPreDecr.class lama\Absyn\EMul.class lama\Absyn\EDiv.class lama\Absyn\EAdd.class lama\Absyn\ESub.class lama\Absyn\ELess.class lama\Absyn\EGreater.class lama\Absyn\ELEq.class lama\Absyn\EGEq.class lama\Absyn\EEq.class lama\Absyn\ENEq.class lama\Absyn\Bool.class lama\Absyn\Bool_true.class lama\Absyn\Bool_false.class lama\Absyn\Type.class lama\Absyn\TInt.class lama\Absyn\TDouble.class lama\Absyn\TBool.class
	 rm -f lama\Absyn\*.class
	 rmdir lama\Absyn
	 rm -f lama\Yylex lama\_cup.cup lama\Yylex.java lama\VisitSkel.java lama\ComposVisitor.java lama\AbstractVisitor.java lama\FoldVisitor.java lama\AllVisitor.java lama\PrettyPrinter.java lama\Skeleton.java lama\Test.java lama\parser.java lama\sym.java lama\*.class
	 rm -f Makefile
	 rmdir -p lama
