// File generated by the BNF Converter (bnfc 2.9.4).

package lama.Absyn;

public abstract class Bool implements java.io.Serializable {
  public abstract <R,A> R accept(Bool.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(lama.Absyn.Bool_true p, A arg);
    public R visit(lama.Absyn.Bool_false p, A arg);

  }

}
