// File generated by the BNF Converter (bnfc 2.9.4).

package lama.Absyn;

public class Bool_false  extends Bool {
  public Bool_false() { }

  public <R,A> R accept(lama.Absyn.Bool.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof lama.Absyn.Bool_false) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
