// File generated by the BNF Converter (bnfc 2.9.4).

package lama.Absyn;

public class EPostDecr  extends Exp {
  public final String ident_;
  public EPostDecr(String p1) { ident_ = p1; }

  public <R,A> R accept(lama.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof lama.Absyn.EPostDecr) {
      lama.Absyn.EPostDecr x = (lama.Absyn.EPostDecr)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
