// File generated by the BNF Converter (bnfc 2.9.4).

package lama.Absyn;

public abstract class Exp implements java.io.Serializable {
  public abstract <R,A> R accept(Exp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(lama.Absyn.EVar p, A arg);
    public R visit(lama.Absyn.EInt p, A arg);
    public R visit(lama.Absyn.EDouble p, A arg);
    public R visit(lama.Absyn.EBool p, A arg);
    public R visit(lama.Absyn.EPostIncr p, A arg);
    public R visit(lama.Absyn.EPostDecr p, A arg);
    public R visit(lama.Absyn.EPreIncr p, A arg);
    public R visit(lama.Absyn.EPreDecr p, A arg);
    public R visit(lama.Absyn.EMul p, A arg);
    public R visit(lama.Absyn.EDiv p, A arg);
    public R visit(lama.Absyn.EAdd p, A arg);
    public R visit(lama.Absyn.ESub p, A arg);
    public R visit(lama.Absyn.ELess p, A arg);
    public R visit(lama.Absyn.EGreater p, A arg);
    public R visit(lama.Absyn.ELEq p, A arg);
    public R visit(lama.Absyn.EGEq p, A arg);
    public R visit(lama.Absyn.EEq p, A arg);
    public R visit(lama.Absyn.ENEq p, A arg);

  }

}
