// File generated by the BNF Converter (bnfc 2.9.4).

package lama.Absyn;

public class Prog  extends Program {
  public final ListStm liststm_;
  public Prog(ListStm p1) { liststm_ = p1; }

  public <R,A> R accept(lama.Absyn.Program.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof lama.Absyn.Prog) {
      lama.Absyn.Prog x = (lama.Absyn.Prog)o;
      return this.liststm_.equals(x.liststm_);
    }
    return false;
  }

  public int hashCode() {
    return this.liststm_.hashCode();
  }


}
