// File generated by the BNF Converter (bnfc 2.9.4).

package lama.Absyn;

public class SAss  extends Stm {
  public final String ident_;
  public final Exp exp_;
  public SAss(String p1, Exp p2) { ident_ = p1; exp_ = p2; }

  public <R,A> R accept(lama.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof lama.Absyn.SAss) {
      lama.Absyn.SAss x = (lama.Absyn.SAss)o;
      return this.ident_.equals(x.ident_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.exp_.hashCode();
  }


}
