// File generated by the BNF Converter (bnfc 2.9.4).

package lama.Absyn;

public class SDecl  extends Stm {
  public final Type type_;
  public final String ident_;
  public SDecl(Type p1, String p2) { type_ = p1; ident_ = p2; }

  public <R,A> R accept(lama.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof lama.Absyn.SDecl) {
      lama.Absyn.SDecl x = (lama.Absyn.SDecl)o;
      return this.type_.equals(x.type_) && this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_.hashCode())+this.ident_.hashCode();
  }


}
