// File generated by the BNF Converter (bnfc 2.9.4).

package lama.Absyn;

public abstract class Stm implements java.io.Serializable {
  public abstract <R,A> R accept(Stm.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(lama.Absyn.SDecl p, A arg);
    public R visit(lama.Absyn.SAss p, A arg);
    public R visit(lama.Absyn.SInit p, A arg);
    public R visit(lama.Absyn.SBlock p, A arg);
    public R visit(lama.Absyn.SPrint p, A arg);

  }

}
