// File generated by the BNF Converter (bnfc 2.9.4).

package lama.Absyn;

public class TArray  extends Type {
  public final Type type_;
  public TArray(Type p1) { type_ = p1; }

  public <R,A> R accept(lama.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof lama.Absyn.TArray) {
      lama.Absyn.TArray x = (lama.Absyn.TArray)o;
      return this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return this.type_.hashCode();
  }


}
